---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: all

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu/trusty64
      box_url: 'https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box'
  - name: centos-6.5
    driver_config:
      box: chef/centos-6.5
      box_url: 'https://atlas.hashicorp.com/chef/boxes/centos-6.5/versions/1.0.0/providers/virtualbox.box'
  - name: centos-7.0
    driver_config:
      box: grampajoe/centos-7.0-ansible
      box_url: 'https://atlas.hashicorp.com/grampajoe/boxes/centos-7.0-ansible/versions/1.0.0/providers/virtualbox.box'

suites:
  - name: default
