---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: all
  playbook: 'tests/integration/default.yml'

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
